name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          # Configuration for the release-please action
          release-type: node
          package-name: '@kommix/mongoose-activity'

          # Use conventional commits for versioning
          # major: feat!: or fix!: (breaking changes)
          # minor: feat: (new features)
          # patch: fix: (bug fixes)

          # Customize changelog sections
          changelog-types: >
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"style","section":"Styles","hidden":true},
              {"type":"refactor","section":"Code Refactoring","hidden":false},
              {"type":"perf","section":"Performance Improvements","hidden":false},
              {"type":"test","section":"Tests","hidden":true},
              {"type":"build","section":"Build System","hidden":true},
              {"type":"ci","section":"Continuous Integration","hidden":true},
              {"type":"chore","section":"Chores","hidden":true}
            ]

          # Include all commits in changelog (not just conventional)
          include-component-in-tag: false

          # Customize pull request title
          pull-request-title-pattern: 'chore: release ${version}'